### ISSUE TITLE
Missing commit() method on cursor object which can create ghost table for small tables

### ISSUE THREAD

**Issue by chrisgt4** [jdglaser/fast-to-sql#10]
The fast_to_sql method is missing cur.commit() on line 160 right before cur.close().  When you are loading smaller data sets, without this commit, the table will appear to be created and able to be queried, however once you close the connection the table will not be saved.  This only happens with smaller tables.  If you add this line, it will prevent this issue going forward.

**Comment by jdglaser** [comment]
The `commit()` method actually happens at the `connection` level not on the `cursor` (see pyodbc [documentation](https://github.com/mkleehammer/pyodbc/wiki/Connection#commit)).

You may notice in the readme that the code example shows `conn.commit()` being called at the end. I made this a specific design choice to have the end user specify when an action should be commited. This provides better security and avoids unexpected actions from taking place. Since table creation (including temp table creation) are saved at the connection level, the user has full control of what to do with the executed sql before committing.

If you do want all actions done at the cursor level to automatically commit, you can turn on [autocommit](https://github.com/mkleehammer/pyodbc/wiki/Connection#autocommit) in pyodbc.

Assuming this addresses your question, I'll be closing this issue for now :smile:
