### ISSUE TITLE
TypeError: can only concatenate str (not "VisitableType") to str

### ISSUE THREAD

**Issue by jjr5330** [jdglaser/fast-to-sql#4]
I am receiving this error when passing my DataFrame through to the fast-to-sql. Any insight on what may be going wrong?

  File "c:/python_venv/projects/sql_queries.py", line 32, in <module>
    fts.to_sql_fast(df, 'current_path', engine, if_exists = 'append', series = False, custom = {col_name: NVARCHAR for col_name in df}, temp = False)
  File "C:\python_venv\pathfile_automation\lib\site-packages\fast_to_SQL\fast_to_SQL.py", line 95, in to_sql_fast
    col_string_create = "(" + ', '.join([cols[i] + " " + sql_dtypes[i] for i in range(len(cols))]) + ")"
  File "C:\python_venv\pathfile_automation\lib\site-packages\fast_to_SQL\fast_to_SQL.py", line 95, in <listcomp>
    col_string_create = "(" + ', '.join([cols[i] + " " + sql_dtypes[i] for i in range(len(cols))]) + ")"
**TypeError: can only concatenate str (not "VisitableType") to str**

**Comment by ibuda** [comment]
I had the same error as you, and apparently this is because of the types of your data.
At least in my case, this happened when I passed data types as `custom` parameter, with data type as sqlalchemy uniqueidentifier, datetime2 and others that are not defined by default in `fast_to_SQL.py` file.

**Comment by jdglaser** [comment]
This issue should be fixed with the new major update version [2.1](https://github.com/jdglaser/fast-to-sql/releases/tag/v2.1). Closing for now, if the issue persists, please open a new issue detailing the error and I will take a look.

Read the updated [readme](https://github.com/jdglaser/fast-to-sql/blob/master/README.md) for new instructions on how to use this package.
