### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'items'

### ISSUE THREAD

**Issue by prasadnaddy** [jdglaser/fast-to-sql#5]
When i tried to insert into SQL DB using :
#### fts.to_sql_fast(df, 'INSERT_DATA', engine3, if_exists = 'append', series = False, custom = False, temp = False)

I get this error:

### File "C:\Users\Datalysys\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fast_to_SQL\fast_to_SQL.py", line 53, in to_sql_fast
    for k,v in custom.items():
AttributeError: 'bool' object has no attribute 'items'

**Comment by jdglaser** [comment]
This issue should be fixed with the major version release [2.1](https://github.com/jdglaser/fast-to-sql/releases/tag/v2.1).

Make sure to read the updated [readme](https://github.com/jdglaser/fast-to-sql/blob/master/README.md) for updated instructions on how to use this package as a lot has changed from previous versions.
